function [meshType, solverType, nV, numDecompose, fileName, epsArap, epsSchur] = SetParameter()
%
%   this function sets up global parameters, such as mesh size, decomposition number and so on
%
%   INPUT:  
%
%   OUTPUT: meshType - the type of the triangulation and the manner to obtain it
%           solverType - the type of the solver
%           nV - mesh size
%           numDecompose - decomposition number
%           fileName - name of obj file
%           epsArap - the convergence error of the local-global method
%           epsSchur - the convergence error of the conjugate method
                   

meshType = listdlg('PromptString', 'Triangulation type', ...
                   'SelectionMode','single', ...
                   'liststring', {'Structured triangulation', ...
                                  'Unstructured triangulation generated by delaunay method', ...
                                  'Unstructured triangulation generated by reading from a file'});


switch meshType
    case {1, 2}
        m1 = listdlg('PromptString', 'Mesh size', 'SelectionMode','single', ...
                     'liststring', {'289', '1089', '4225', '16641', '66049', '263169'}) + 3;
        nV = (2^m1 + 1)^2;
        fileName = 'None';
    case 3
        fileName = listdlg('PromptString', 'Mesh file', ...
                           'SelectionMode','single', ...
                           'liststring', {'ball', 'camelhead_slim', 'face'});
        switch fileName
            case 1
                [V, ~, ~, ~] = readObj('NewtonParam/ball');
            case 2
                [V, ~, ~, ~] = readObj('NewtonParam/camelhead_slim');
            case 3
                [V, ~, ~, ~] = readObj('NewtonParam/face');
            otherwise
                quit(1);
        end
        nV = size(V, 1);
    otherwise
        quit(1);
end


if nV <= 200
    fprintf('No need to apply decomposition method./n');
    quit(1);
elseif nV <= 1000
	m2 = listdlg('PromptString', 'Decomposition number', 'SelectionMode','single', 'liststring', {'4'});
elseif nV <= 4000
    m2 = listdlg('PromptString', 'Decomposition number', 'SelectionMode','single', 'liststring', {'4', '16'});
elseif nV <= 16000
    m2 = listdlg('PromptString', 'Decomposition number', 'SelectionMode','single', 'liststring', {'4', '16', '64'});
else
    m2 = listdlg('PromptString', 'Decomposition number', 'SelectionMode','single', 'liststring', {'4', '16', '64', '256'});
end
numDecompose = 2^(2 * m2);


solverType = listdlg('PromptString', 'Solver type', 'SelectionMode','single', ...
                     'liststring', {'Direct solver', 'Conjugate solver', 'Preconditioned conjugate solver'});


eps = floor(1.5 * log10(1.0 / nV));
epsArap = 10^eps;
epsSchur = 10^eps;


end